/* eslint-disable no-use-before-define */

declare module "*.vue" {
    import Vue from "vue";
    export default Vue;
}

declare module "vuex-map-fields" {
    import * as vuexMapFields from "vuex-map-fields";
    export default vuexMapFields;
}

interface UserSaveObject {
    createDate?: string;
    createByUrn?: string;
    lastEditByUrn: string;
    lastEditDate: string;
}
export type PageDataObject = UserSaveObject & {
    urn: string;
    names: string[];
    name: string;
    summary: string;
    description?: string;
    descriptionHtml?: string;
    serviceOutput: ServiceOutput;
    operationImpls: (OperationImpl & { pageTemplate: string })[];
    purposeUrns: string[];
    boundToEntityTypeUrn?: string;
    entityTypeUrns: string[];
    combinedItemUrns: string[];
    inactive: boolean;
    deprecated?: Boolean;
    lastEditDateObs?: string;
    lastEditByUrnObs?: string;
    textSet?: string[];
    test?: string;
    pages: Page[];
};

export interface OperationImpl {
    operation: string;
    method: string;
    pageTemplate?: string;
    executionScriptUrn?: string;
    securityFunctionGroups: any[];
    actionImpls: ActionImpl[];
}

export interface ActionImpl {
    action: string;
    securityFunctionGroups: string[];
}

export interface Page {
    urn: string;
}

export interface ServiceOutput {
    outputContentTypeUrn: string;
    oldContentType: string;
    maxAge: string;
}

export type QueryDataObject = UserSaveObject & {
    urn: string;
    name: string;
    summary: string;
    queryString: string;
    securityFunctionUrns: string[];
    boundToEntityTypeUrn?: string;
    childQueries?: ChildQuery[];
    inactive: boolean;
    queryEngineUrn?: string;
    dataSpaceUrn?: string;
    queryParams?: QueryParam[];
};

export interface ChildQuery {
    urn: string;
    queryString: string;
    dataSpaceUrn: string;
    queryParams?: QueryParam[];
}

export interface QueryParam {
    codeName: string;
    valueTypeUrn:
        | "urn:com:loki:core:model:types:string"
        | "urn:com:loki:core:model:types:bool"
        | "urn:com:loki:core:model:types:integer"
        | "urn:com:loki:core:model:types:date"
        | "urn:com:loki:core:model:types:decimal";
}

export interface WebserviceDataObject {
    urn: string;
    entityTypeUrns: string[];
    summary: string;
    description: string;
    operationImpls: (OperationImpl & { executionScriptUrn: string })[];
    purposeUrns: string[];
    boundToEntityTypeUrn: null;
    name: string;
    inactive: boolean;
    lastEditByUrn: string;
    lastEditDate: string;
}

// Generated by https://quicktype.io

export interface LokiEntityType {
    urn: string;
    entityTypeUrns: string[];
    names: string[];
    name: string;
    summary: null;
    description: string;
    descriptionHtml: null;
    fields: LokiFieldtype[];
    modifiers: any[];
    instanceEntityTypeUrn: string;
    purposeUrns: string[];
    inactive: null;
    createDate: string;
    lastEditDate: string;
    createByUrn: string;
    lastEditByUrn: string;
}

export interface LokiFieldtype {
    entityTypeUrns: any[];
    codeName: string;
    propertyViewUrn: string;
    modifierUrns: any[];
    modifierValues: FieldModifierValue[];
    valueViewUrn: null;
    dataConverterUrn: null | string;
    indexValue: number | null;
    joinTypeUrn: null;
    propertyUrn: null;
    dateFormat: null;
    estMaxLength: null;
    estMaxPrecision: null;
    estMaxScale: null;
    valueTypeUrn: null;
}

export interface FieldModifierValue {
    modifierUrn: string;
    modifierValue: string;
}

const RelativityDataObjectType = {
    urn: "urn:com:reedsmith:delorean:model:types:relativityDataObject",
    entityTypeUrns: ["urn:com:loki:meta:model:types:entityView"],
    names: ["Relativity Data Object"],
    name: "Relativity Data Object",
    summary: null,
    description:
        "Extended view of a entity view that has all we need for the modeler tool.",
    descriptionHtml: null,
    fields: [
        {
            entityTypeUrns: [],
            codeName: "entityTypeUrns",
            propertyViewUrn: "urn:com:loki:core:model:properties:entityType",
            modifierUrns: [],
            modifierValues: [],
            valueViewUrn: null,
            dataConverterUrn: null,
            indexValue: null,
            joinTypeUrn: null,
            propertyUrn: null,
            dateFormat: null,
            estMaxLength: null,
            estMaxPrecision: null,
            estMaxScale: null,
            valueTypeUrn: null,
        },
        {
            entityTypeUrns: [],
            codeName: "artifactId",
            propertyViewUrn:
                "urn:com:reedsmith:delorean:model:properties:ArtifactID",
            modifierUrns: [],
            modifierValues: [],
            valueViewUrn: null,
            dataConverterUrn: null,
            indexValue: 0,
            joinTypeUrn: null,
            propertyUrn: null,
            dateFormat: null,
            estMaxLength: null,
            estMaxPrecision: null,
            estMaxScale: null,
            valueTypeUrn: null,
        },
        {
            entityTypeUrns: [],
            codeName: "descriptorArtifactTypeId",
            propertyViewUrn:
                "urn:com:reedsmith:delorean:model:properties:descriptorArtifactTypeId",
            modifierUrns: [],
            modifierValues: [],
            valueViewUrn: null,
            dataConverterUrn: null,
            indexValue: 0,
            joinTypeUrn: null,
            propertyUrn: null,
            dateFormat: null,
            estMaxLength: null,
            estMaxPrecision: null,
            estMaxScale: null,
            valueTypeUrn: null,
        },
        {
            entityTypeUrns: [],
            codeName: "relativityTextIdentifier",
            propertyViewUrn: "urn:com:loki:core:model:properties:name",
            modifierUrns: [],
            modifierValues: [],
            valueViewUrn: null,
            dataConverterUrn: null,
            indexValue: 0,
            joinTypeUrn: null,
            propertyUrn: null,
            dateFormat: null,
            estMaxLength: null,
            estMaxPrecision: null,
            estMaxScale: null,
            valueTypeUrn: null,
        },
        {
            entityTypeUrns: [],
            codeName: "summary",
            propertyViewUrn: "urn:com:loki:core:model:properties:summary",
            modifierUrns: [],
            modifierValues: [],
            valueViewUrn: null,
            dataConverterUrn: null,
            indexValue: null,
            joinTypeUrn: null,
            propertyUrn: null,
            dateFormat: null,
            estMaxLength: null,
            estMaxPrecision: null,
            estMaxScale: null,
            valueTypeUrn: null,
        },
        {
            entityTypeUrns: [],
            codeName: "names",
            propertyViewUrn: "urn:com:loki:core:model:properties:names",
            modifierUrns: [],
            modifierValues: [],
            valueViewUrn: null,
            dataConverterUrn: null,
            indexValue: null,
            joinTypeUrn: null,
            propertyUrn: null,
            dateFormat: null,
            estMaxLength: null,
            estMaxPrecision: null,
            estMaxScale: null,
            valueTypeUrn: null,
        },
        {
            entityTypeUrns: [],
            codeName: "description",
            propertyViewUrn: "urn:com:loki:core:model:properties:description",
            modifierUrns: [],
            modifierValues: [],
            valueViewUrn: null,
            dataConverterUrn: null,
            indexValue: null,
            joinTypeUrn: null,
            propertyUrn: null,
            dateFormat: null,
            estMaxLength: null,
            estMaxPrecision: null,
            estMaxScale: null,
            valueTypeUrn: null,
        },
        {
            entityTypeUrns: [],
            codeName: "descriptionHtml",
            propertyViewUrn: "urn:com:loki:core:model:properties:description",
            modifierUrns: [],
            modifierValues: [
                {
                    modifierUrn: "urn:com:loki:core:model:modifiers:format",
                    modifierValue: "urn:com:loki:core:model:formats:lokiHtml",
                },
            ],
            valueViewUrn: null,
            dataConverterUrn:
                "urn:com:loki:core:model:formats:lokiHtml:converters:html",
            indexValue: null,
            joinTypeUrn: null,
            propertyUrn: null,
            dateFormat: null,
            estMaxLength: null,
            estMaxPrecision: null,
            estMaxScale: null,
            valueTypeUrn: null,
        },
        {
            entityTypeUrns: [],
            codeName: "fields",
            propertyViewUrn: "urn:com:loki:meta:model:properties:field",
            modifierUrns: [],
            modifierValues: [],
            valueViewUrn: null,
            dataConverterUrn: null,
            indexValue: null,
            joinTypeUrn: null,
            propertyUrn: null,
            dateFormat: null,
            estMaxLength: null,
            estMaxPrecision: null,
            estMaxScale: null,
            valueTypeUrn: null,
        },
        {
            entityTypeUrns: [],
            codeName: "modifiers",
            propertyViewUrn: "urn:com:loki:meta:model:properties:modifierImpl",
            modifierUrns: [],
            modifierValues: [],
            valueViewUrn: null,
            dataConverterUrn: null,
            indexValue: null,
            joinTypeUrn: null,
            propertyUrn: null,
            dateFormat: null,
            estMaxLength: null,
            estMaxPrecision: null,
            estMaxScale: null,
            valueTypeUrn: null,
        },
        {
            entityTypeUrns: [],
            codeName: "instanceEntityTypeUrn",
            propertyViewUrn:
                "urn:com:loki:meta:model:properties:instanceEntityTypeUrn",
            modifierUrns: [],
            modifierValues: [],
            valueViewUrn: null,
            dataConverterUrn: null,
            indexValue: null,
            joinTypeUrn: null,
            propertyUrn: null,
            dateFormat: null,
            estMaxLength: null,
            estMaxPrecision: null,
            estMaxScale: null,
            valueTypeUrn: null,
        },
        {
            entityTypeUrns: [],
            codeName: "purposeUrns",
            propertyViewUrn: "urn:com:loki:core:model:properties:purposeUrns",
            modifierUrns: [],
            modifierValues: [],
            valueViewUrn: null,
            dataConverterUrn: null,
            indexValue: null,
            joinTypeUrn: null,
            propertyUrn: null,
            dateFormat: null,
            estMaxLength: null,
            estMaxPrecision: null,
            estMaxScale: null,
            valueTypeUrn: null,
        },
        {
            entityTypeUrns: [],
            codeName: "inactive",
            propertyViewUrn: "urn:com:loki:core:model:properties:inactive",
            modifierUrns: [],
            modifierValues: [],
            valueViewUrn: null,
            dataConverterUrn: null,
            indexValue: null,
            joinTypeUrn: null,
            propertyUrn: null,
            dateFormat: null,
            estMaxLength: null,
            estMaxPrecision: null,
            estMaxScale: null,
            valueTypeUrn: null,
        },
        {
            entityTypeUrns: [],
            codeName: "createDate",
            propertyViewUrn: "urn:com:loki:core:model:properties:createDate",
            modifierUrns: [],
            modifierValues: [],
            valueViewUrn: null,
            dataConverterUrn: null,
            indexValue: null,
            joinTypeUrn: null,
            propertyUrn: null,
            dateFormat: null,
            estMaxLength: null,
            estMaxPrecision: null,
            estMaxScale: null,
            valueTypeUrn: null,
        },
        {
            entityTypeUrns: [],
            codeName: "lastEditDate",
            propertyViewUrn: "urn:com:loki:core:model:properties:lastEditDate",
            modifierUrns: [],
            modifierValues: [],
            valueViewUrn: null,
            dataConverterUrn: null,
            indexValue: null,
            joinTypeUrn: null,
            propertyUrn: null,
            dateFormat: null,
            estMaxLength: null,
            estMaxPrecision: null,
            estMaxScale: null,
            valueTypeUrn: null,
        },
        {
            entityTypeUrns: [],
            codeName: "createByUrn",
            propertyViewUrn: "urn:com:loki:core:model:properties:createByUrn",
            modifierUrns: [],
            modifierValues: [],
            valueViewUrn: null,
            dataConverterUrn: null,
            indexValue: null,
            joinTypeUrn: null,
            propertyUrn: null,
            dateFormat: null,
            estMaxLength: null,
            estMaxPrecision: null,
            estMaxScale: null,
            valueTypeUrn: null,
        },
        {
            entityTypeUrns: [],
            codeName: "lastEditByUrn",
            propertyViewUrn: "urn:com:loki:core:model:properties:lastEditByUrn",
            modifierUrns: [],
            modifierValues: [],
            valueViewUrn: null,
            dataConverterUrn: null,
            indexValue: null,
            joinTypeUrn: null,
            propertyUrn: null,
            dateFormat: null,
            estMaxLength: null,
            estMaxPrecision: null,
            estMaxScale: null,
            valueTypeUrn: null,
        },
    ],
    modifiers: [],
    instanceEntityTypeUrn: "urn:com:loki:meta:model:types:entityView",
    purposeUrns: ["urn:com:loki:meta:data:modelPurposeSet#metaModel"],
    inactive: null,
    createDate: "2021-03-13T13:02:37.997Z",
    lastEditDate: "2021-03-14T13:15:34.653Z",
    createByUrn: "urn:com:reedsmith:domain:security:users:benKoplin",
    lastEditByUrn: "urn:com:reedsmith:domain:security:users:benKoplin",
};
