# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to Loki

# Uncomment the lines below to enable the workflow.
on:
  workflow_dispatch:
#   push:
#     branches: [ main ]


jobs:
  makeEnv:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    outputs:
      VITE_CLOUD_CODE_NAME: ${{ steps.dotenv.outputs.VITE_CLOUD_CODE_NAME}}
      VITE_APP_CODE_NAME: ${{ steps.dotenv.outputs.VITE_APP_CODE_NAME }}
      VITE_PAGE_NAME: ${{ steps.dotenv.outputs.VITE_PAGE_NAME }}
      VITE_PAGE_CODE_NAME: ${{ steps.dotenv.outputs.VITE_PAGE_CODE_NAME }}        
      VITE_PG_DATASPACE: ${{ steps.dotenv.outputs.VITE_PG_DATASPACE }}        
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get .env variables
        id: dotenv
        # You may pin to the exact commit or the version.
        # uses: falti/dotenv-action@cb77e3cb51b636f6833ceeb6928bf06ff66e82fa
        uses: falti/dotenv-action@v0.2.5
        with:
          # the path to the .env file (including file name)
          path: .env # default is .env
          # whether to log the variables to output or not
          log-variables: true # optional, default is false
  build:
    needs: makeEnv
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      LOKI_USERNAME: ${{ secrets.LOKI_USERNAME }}
      LOKI_PASSWORD: ${{ secrets.LOKI_PASSWORD }}
      LOKI_USER_URN: ${{ secrets.LOKI_USER_URN }}
      VITE_CLOUD_CODE_NAME: ${{ needs.makeEnv.outputs.VITE_CLOUD_CODE_NAME}}
      VITE_APP_CODE_NAME: ${{ needs.makeEnv.outputs.VITE_APP_CODE_NAME }}
      VITE_PAGE_NAME: ${{ needs.makeEnv.outputs.VITE_PAGE_NAME }}
      VITE_PAGE_CODE_NAME: ${{ needs.makeEnv.outputs.VITE_PAGE_CODE_NAME }}   
      VITE_PG_DATASPACE: ${{ needs.makeEnv.outputs.VITE_PG_DATASPACE }}   
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install --legacy-peer-deps
    - name: Build and Upload to Loki
      run: npm run build --if-present
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ needs.makeEnv.outputs.VITE_PAGE_CODE_NAME }} 
        path: |
          dist
          !dist/**/*.md
